name: release
on:
  workflow_dispatch:
    inputs:
      auto_publish:
        description: 'Automatically answer yes to the confirmation prompt for publishing.'
        default: true
        type: boolean

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
      id-token: write # needed for provenance data generation
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: install npm
        run: npm ci

      - name: build
        run: npx nx run-many --target=build --no-cloud

      - name: git config
        run: |
          git config user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config user.email "$(git --no-pager log --format=format:'%ae' -n 1)"

      - name: Release
        if: inputs.auto_publish
        run: npx nx release --excludeTaskDependencies --yes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true

      - name: Release Publish Dry-Run
        if: ${{ !inputs.auto_publish }}
        run: npx nx release publish --excludeTaskDependencies --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
